first iteration of code
GolosChain/meta-service pull request #1
Opened 2018-12-18 10:33 UTC by Bacher

2018-12-18 11:15 UTC, beautyfree approved these changes

2018-12-18 11:42 UTC, Format-X22 requested changes

2018-12-18 11:42 UTC, Format-X22 commented on .env.example
> +GLS_MONGO_CONNECT=mongodb://seen_counter_mongo/counter
А почему не как везде? В других микросервисах универсальная ссылка.

2018-12-18 11:42 UTC, Format-X22 commented on .env.example
> +GLS_MONGO_EXTERNAL_PORT=27017
Если это для внешнего доступа - хост ещё надо бы, посмотри как в регистрации.

2018-12-18 11:42 UTC, Format-X22 commented on README.md
> +
Ну есть же пример как дока в других микросервисах пишется :) Или так и было задумано?

2018-12-18 11:42 UTC, Format-X22 commented on package.json
> +  "author": "Golos Team",
Обычно golos.io

2018-12-18 11:42 UTC, Format-X22 commented on src/Main.js
> +class Main extends Basic {
BasicMain избавит тебя от половины кода что в этом файле есть.

2018-12-18 11:42 UTC, Format-X22 commented on src/index.js
> +const core = require('gls-core-service');
utils.defaultStarter и твой файл будет в одну строку кода. Посмотри другие микросервисы.

2018-12-18 11:42 UTC, Format-X22 commented on src/model/Post.js
> +        postLink: {
А не пермлинк?

2018-12-18 11:42 UTC, Format-X22 commented on src/services/Connector.js
> +const BasicConnector = core.services.Connector;
Можно и без пробела сверху :) Но не настаиваю.

2018-12-18 11:42 UTC, Format-X22 commented on src/services/Connector.js
> +        bindAll(this, ['_getPostSeenCount', '_recordSeen']);
Прикольно конечно, но... текст и явный код вещи разные. Лучше по возможности не делать так.

2018-12-18 11:42 UTC, Format-X22 commented on src/services/Connector.js
> +        bindAll(this, ['_getPostSeenCount', '_recordSeen']);
Добавлю ещё что далеко не всегда там this может быть, посмотри фасад.

2018-12-18 11:42 UTC, Format-X22 commented on src/services/Connector.js
> +                recordSeen: this._recordSeen,
recordPostSeen, в будущем их поболее быть может

2018-12-18 11:42 UTC, Format-X22 commented on src/services/Connector.js
> +            'seen_counter_get_posts_seen_count_api',
Длинновато.

2018-12-18 11:42 UTC, Format-X22 commented on src/services/Connector.js
> +            status: 'OK',
Нет необходимости, пустой ответ сам ответит что статус ок, можно не делать ретурн.

2018-12-18 11:42 UTC, Format-X22 commented on src/services/CurrentState.js
> +const STATE_DIR = path.join(__dirname, '../../state');
Что-то прям рассадник пропусков строк, не компактно выглядит.

2018-12-18 11:42 UTC, Format-X22 commented on src/services/CurrentState.js
> +                    await fs.readFile(path.join(STATE_DIR, fileName))
Поясни причину почему файл?!

2018-12-18 11:42 UTC, Format-X22 commented on src/services/CurrentState.js
> +        this._pools = times(HISTORY_LIMIT, () => new Set());
А нам нужен лимит?

2018-12-18 11:42 UTC, Format-X22 commented on src/services/Connector.js
> +        if (!postLink || !fingerPrint) {
А ip? Он всегда определяется всё-равно.

2018-12-18 13:06 UTC, Bacher commented on .env.example
> +GLS_MONGO_EXTERNAL_PORT=27017
Внешнего доступа нет, я её объявляю чтобы не было конфликта на локальной машине. Иначе несколько микросервисов невозможно нормально запустить.

2018-12-18 13:07 UTC, Bacher commented on src/Main.js
> +class Main extends Basic {
А, точно, забыл тут.

2018-12-18 13:09 UTC, Bacher commented on .env.example
> +GLS_MONGO_CONNECT=mongodb://seen_counter_mongo/counter
В моих микросервисах везде так. А как по другому?

2018-12-18 13:16 UTC, Bacher commented on src/services/CurrentState.js
> +        this._pools = times(HISTORY_LIMIT, () => new Set());
Условие задачи, отслеживать дубликаты в течении 24-х часов.

2018-12-18 13:23 UTC, bacher commented on src/services/CurrentState.js
> +const STATE_DIR = path.join(__dirname, '../../state');
Поправил.

2018-12-18 13:24 UTC, bacher commented on src/services/CurrentState.js
> +                    await fs.readFile(path.join(STATE_DIR, fileName))
В файлы удобно бекапить дубликаты за час.
Каждый час сохранется дамп за час.
При recovery из файлов считываются списки.

2018-12-18 13:25 UTC, bacher commented on README.md
> +
Поправил.

2018-12-18 13:27 UTC, bacher commented on src/model/Post.js
> +        postLink: {
postLink'ом мы называем у себя урлы формата `author/perm-link`, ну полный link по сути на пост.

2018-12-18 13:30 UTC, Bacher commented on src/services/Connector.js
> +        bindAll(this, ['_getPostSeenCount', '_recordSeen']);
```
this._getPostSeenCount = this._getPostSeenCount.bind(this;
```
Я считаю что это дублирование кода, это может приводить к ошибкам.

2018-12-18 13:32 UTC, Bacher commented on src/services/Connector.js
> +            'seen_counter_get_posts_seen_count_api',
Это метрика, не имеет значения какая тут длинна. Я считаю.

2018-12-18 13:58 UTC, Format-X22 commented on src/services/CurrentState.js
> +                    await fs.readFile(path.join(STATE_DIR, fileName))
Но почему не в базу? Чем файл лучше?

2018-12-18 14:00 UTC, Format-X22 commented on .env.example
> +GLS_MONGO_CONNECT=mongodb://seen_counter_mongo/counter
GLS_MONGO_CONNECT=mongodb://mongo/admin

2018-12-18 14:01 UTC, Format-X22 commented on .env.example
> +GLS_MONGO_EXTERNAL_PORT=27017
Для этого есть .env в котором ты конфигуришь как надо если дефолты не подходят.

2018-12-18 14:26 UTC, bacher commented on .env.example
> +GLS_MONGO_CONNECT=mongodb://seen_counter_mongo/counter
Я так не смогу запустить несколько сервисов не корректируя `docker-compose.yml` файлы, так не пойдет.

2018-12-18 14:27 UTC, bacher commented on .env.example
> +GLS_MONGO_EXTERNAL_PORT=27017
Так я и добавил этот параметр в .env, раньше там было 127.0.0.1:27017:27017.

2018-12-18 14:28 UTC, bacher commented on .env.example
> +GLS_MONGO_CONNECT=mongodb://seen_counter_mongo/counter
Плюс мы раньше уже обсуждали использование дефолтной базы, не я один считаю что это плохой подход использовать базу `admin`.

2018-12-18 14:30 UTC, Bacher commented on .env.example
> +GLS_MONGO_EXTERNAL_PORT=27017
Я могу в целом вообще удалить эту строку:
![image](https://user-images.githubusercontent.com/2598671/50160496-92341380-02ea-11e9-8bc9-4d2de4f88b8d.png)

Я просто добавлял её по образу подобию с самого начала.

2018-12-19 10:45 UTC, Bacher commented on .env.example
> +GLS_MONGO_EXTERNAL_PORT=27017
Добавил `GLS_MONGO_EXTERNAL_HOST`

2018-12-19 11:09 UTC, Format-X22 approved these changes

2018-12-19 13:55 UTC, merged