Cyber Alpha
GolosChain/meta-service pull request #13
Opened 2019-04-22 09:43 UTC by Format-X22

2019-06-04 11:23 UTC, bacher approved these changes

2019-07-09 16:48 UTC, bacher approved these changes

2019-07-10 08:34 UTC, IvanBlacky requested changes

2019-07-10 08:34 UTC, IvanBlacky commented on src/controllers/ViewCount.js
> +        // if (!postLink || !fingerPrint || !clientRequestIp) {
Закомментированный код?

2019-08-01 16:16 UTC, IvanBlacky approved these changes

2019-08-01 16:16 UTC, merged