2 add user online logic
GolosChain/meta-service pull request #3
Opened 2018-12-26 10:22 UTC by Bacher

2018-12-26 10:36 UTC, Format-X22 requested changes

2018-12-26 10:36 UTC, Format-X22 commented on src/model/User.js
> +        lastOnlineTs: {
lastOnlineDate

2018-12-26 10:36 UTC, Format-X22 commented on src/services/Connector.js
> +    async _markUserOnline({ username }) {
Обычно используется имя параметра user, так везде, не стоит менять.

2018-12-26 10:36 UTC, Format-X22 commented on src/services/Connector.js
> +        if (!username) {
Как может быть так что нет юзера?

2018-12-26 10:36 UTC, Format-X22 commented on src/services/Connector.js
> +        await this._currentState.markUserOnline(username);
Почему бы сразу не делать это в контроллере?

2018-12-26 10:36 UTC, Format-X22 commented on src/services/Connector.js
> +        for (const username of usernames) {
Лучше делать это всё сразу в контроллере. Вообще дополнительные методы в коннекторе нужны только если у тебя какая-то общая логика, которую нельзя просто так взять и вынести в контроллер - как в регистрации с шагами всякими, и то - можно было бы сделать верхнеуровневый контроллер, который всё бы это делал и проксировал вызов дальше. Лучше использовать коннектор как роутинг запросов со вспомогательными методами, проксирующими вызовы дальше в соответствующие контроллеры.

2018-12-26 10:36 UTC, Format-X22 commented on src/services/Connector.js
> +    async _getUsersLastOnline({ usernames }) {
Как так выходит что их массив если каждый юзер по факту отмечает себя онлайн?

2018-12-27 09:09 UTC, Bacher commented on src/services/Connector.js
> +    async _markUserOnline({ username }) {
На frontend везде используется username, user всегда является объектом представления user'a. Мне кажется это логично.

Сразу понятно что это строка.

2018-12-27 09:20 UTC, Bacher commented on src/model/User.js
> +        lastOnlineTs: {
Просто формат который обычно называется Date это строки типа
`"2018-12-03"`

Если передаются данные формата
`"2018-12-03T15:03:10.375Z"`
это все же Таймстемп и хочется сразу видеть эту разницу сразу по названию поля.

2018-12-28 09:43 UTC, Format-X22 approved these changes

2018-12-28 09:43 UTC, Format-X22 commented on src/model/User.js
> +        lastOnlineTs: {
lastOnlineAt

2018-12-28 16:33 UTC, merged